name: "Deploy pages"
on: push

jobs:
  export-web:
    name: Web Export
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:3.4.4
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: setup
        run: |
          mkdir -v -p ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates/3.4.4.stable ~/.local/share/godot/templates/3.4.4.stable
      - name: build
        run: |
          mkdir -v -p build/web
          godot -v --export "HTML5" build/web/index.html
      - name: install rsync
        run: |
          apt-get update && apt-get install -y rsync
      - name: deploy to pages
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          branch: gh-pages
          folder: latest
